/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Esper2MaudeStandaloneSetup extends Esper2MaudeStandaloneSetupGenerated {

	def static void doSetup() {
		new Esper2MaudeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
