/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.esper2Maude.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class Esper2MaudeFactoryImpl extends EFactoryImpl implements Esper2MaudeFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static Esper2MaudeFactory init()
  {
    try
    {
      Esper2MaudeFactory theEsper2MaudeFactory = (Esper2MaudeFactory)EPackage.Registry.INSTANCE.getEFactory(Esper2MaudePackage.eNS_URI);
      if (theEsper2MaudeFactory != null)
      {
        return theEsper2MaudeFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new Esper2MaudeFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Esper2MaudeFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case Esper2MaudePackage.MODEL: return createModel();
      case Esper2MaudePackage.SCHEMA: return createSchema();
      case Esper2MaudePackage.EVENT_PROPERTY: return createEventProperty();
      case Esper2MaudePackage.PATTERN: return createPattern();
      case Esper2MaudePackage.WINDOW: return createWindow();
      case Esper2MaudePackage.WHERE_FILTER: return createWhereFilter();
      case Esper2MaudePackage.FILTER_FROM: return createFilterFrom();
      case Esper2MaudePackage.FOLLOWED_BY: return createFollowedBy();
      case Esper2MaudePackage.SUB_FILTER_FOLLOWED_BY: return createSubFilterFollowedBy();
      case Esper2MaudePackage.EVERY: return createEvery();
      case Esper2MaudePackage.FILTER_EVENT: return createFilterEvent();
      case Esper2MaudePackage.FILTER_PART: return createFilterPart();
      case Esper2MaudePackage.FILTER_OPERATOR: return createFilterOperator();
      case Esper2MaudePackage.COMPARISON_OPERATOR: return createComparisonOperator();
      case Esper2MaudePackage.LOGICAL_OPERATOR: return createLogicalOperator();
      case Esper2MaudePackage.EVENT: return createEvent();
      case Esper2MaudePackage.NON_LAST_SELECT_ENTRY: return createNonLastSelectEntry();
      case Esper2MaudePackage.LAST_SELECT_ENTRY: return createLastSelectEntry();
      case Esper2MaudePackage.SELECT_ENTRY: return createSelectEntry();
      case Esper2MaudePackage.FIELD: return createField();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Schema createSchema()
  {
    SchemaImpl schema = new SchemaImpl();
    return schema;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EventProperty createEventProperty()
  {
    EventPropertyImpl eventProperty = new EventPropertyImpl();
    return eventProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Pattern createPattern()
  {
    PatternImpl pattern = new PatternImpl();
    return pattern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Window createWindow()
  {
    WindowImpl window = new WindowImpl();
    return window;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WhereFilter createWhereFilter()
  {
    WhereFilterImpl whereFilter = new WhereFilterImpl();
    return whereFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FilterFrom createFilterFrom()
  {
    FilterFromImpl filterFrom = new FilterFromImpl();
    return filterFrom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FollowedBy createFollowedBy()
  {
    FollowedByImpl followedBy = new FollowedByImpl();
    return followedBy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubFilterFollowedBy createSubFilterFollowedBy()
  {
    SubFilterFollowedByImpl subFilterFollowedBy = new SubFilterFollowedByImpl();
    return subFilterFollowedBy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Every createEvery()
  {
    EveryImpl every = new EveryImpl();
    return every;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FilterEvent createFilterEvent()
  {
    FilterEventImpl filterEvent = new FilterEventImpl();
    return filterEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FilterPart createFilterPart()
  {
    FilterPartImpl filterPart = new FilterPartImpl();
    return filterPart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FilterOperator createFilterOperator()
  {
    FilterOperatorImpl filterOperator = new FilterOperatorImpl();
    return filterOperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComparisonOperator createComparisonOperator()
  {
    ComparisonOperatorImpl comparisonOperator = new ComparisonOperatorImpl();
    return comparisonOperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LogicalOperator createLogicalOperator()
  {
    LogicalOperatorImpl logicalOperator = new LogicalOperatorImpl();
    return logicalOperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event createEvent()
  {
    EventImpl event = new EventImpl();
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NonLastSelectEntry createNonLastSelectEntry()
  {
    NonLastSelectEntryImpl nonLastSelectEntry = new NonLastSelectEntryImpl();
    return nonLastSelectEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LastSelectEntry createLastSelectEntry()
  {
    LastSelectEntryImpl lastSelectEntry = new LastSelectEntryImpl();
    return lastSelectEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SelectEntry createSelectEntry()
  {
    SelectEntryImpl selectEntry = new SelectEntryImpl();
    return selectEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Field createField()
  {
    FieldImpl field = new FieldImpl();
    return field;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Esper2MaudePackage getEsper2MaudePackage()
  {
    return (Esper2MaudePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static Esper2MaudePackage getPackage()
  {
    return Esper2MaudePackage.eINSTANCE;
  }

} //Esper2MaudeFactoryImpl
