/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage;
import org.xtext.example.mydsl.esper2Maude.Field;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.impl.FieldImpl#getStar <em>Star</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.impl.FieldImpl#getEventVariable <em>Event Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.impl.FieldImpl#getEventPropName <em>Event Prop Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FieldImpl extends MinimalEObjectImpl.Container implements Field
{
  /**
   * The default value of the '{@link #getStar() <em>Star</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStar()
   * @generated
   * @ordered
   */
  protected static final String STAR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStar() <em>Star</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStar()
   * @generated
   * @ordered
   */
  protected String star = STAR_EDEFAULT;

  /**
   * The default value of the '{@link #getEventVariable() <em>Event Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventVariable()
   * @generated
   * @ordered
   */
  protected static final String EVENT_VARIABLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEventVariable() <em>Event Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventVariable()
   * @generated
   * @ordered
   */
  protected String eventVariable = EVENT_VARIABLE_EDEFAULT;

  /**
   * The default value of the '{@link #getEventPropName() <em>Event Prop Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventPropName()
   * @generated
   * @ordered
   */
  protected static final String EVENT_PROP_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEventPropName() <em>Event Prop Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventPropName()
   * @generated
   * @ordered
   */
  protected String eventPropName = EVENT_PROP_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FieldImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Esper2MaudePackage.Literals.FIELD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStar()
  {
    return star;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStar(String newStar)
  {
    String oldStar = star;
    star = newStar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Esper2MaudePackage.FIELD__STAR, oldStar, star));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEventVariable()
  {
    return eventVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEventVariable(String newEventVariable)
  {
    String oldEventVariable = eventVariable;
    eventVariable = newEventVariable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Esper2MaudePackage.FIELD__EVENT_VARIABLE, oldEventVariable, eventVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEventPropName()
  {
    return eventPropName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEventPropName(String newEventPropName)
  {
    String oldEventPropName = eventPropName;
    eventPropName = newEventPropName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Esper2MaudePackage.FIELD__EVENT_PROP_NAME, oldEventPropName, eventPropName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Esper2MaudePackage.FIELD__STAR:
        return getStar();
      case Esper2MaudePackage.FIELD__EVENT_VARIABLE:
        return getEventVariable();
      case Esper2MaudePackage.FIELD__EVENT_PROP_NAME:
        return getEventPropName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Esper2MaudePackage.FIELD__STAR:
        setStar((String)newValue);
        return;
      case Esper2MaudePackage.FIELD__EVENT_VARIABLE:
        setEventVariable((String)newValue);
        return;
      case Esper2MaudePackage.FIELD__EVENT_PROP_NAME:
        setEventPropName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Esper2MaudePackage.FIELD__STAR:
        setStar(STAR_EDEFAULT);
        return;
      case Esper2MaudePackage.FIELD__EVENT_VARIABLE:
        setEventVariable(EVENT_VARIABLE_EDEFAULT);
        return;
      case Esper2MaudePackage.FIELD__EVENT_PROP_NAME:
        setEventPropName(EVENT_PROP_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Esper2MaudePackage.FIELD__STAR:
        return STAR_EDEFAULT == null ? star != null : !STAR_EDEFAULT.equals(star);
      case Esper2MaudePackage.FIELD__EVENT_VARIABLE:
        return EVENT_VARIABLE_EDEFAULT == null ? eventVariable != null : !EVENT_VARIABLE_EDEFAULT.equals(eventVariable);
      case Esper2MaudePackage.FIELD__EVENT_PROP_NAME:
        return EVENT_PROP_NAME_EDEFAULT == null ? eventPropName != null : !EVENT_PROP_NAME_EDEFAULT.equals(eventPropName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (star: ");
    result.append(star);
    result.append(", eventVariable: ");
    result.append(eventVariable);
    result.append(", eventPropName: ");
    result.append(eventPropName);
    result.append(')');
    return result.toString();
  }

} //FieldImpl
