/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractEsper2MaudeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Esper2MaudeRuntimeModule extends AbstractEsper2MaudeRuntimeModule {
}
