/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getGt <em>Gt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getGe <em>Ge</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getEq <em>Eq</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getNeq <em>Neq</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getLt <em>Lt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getLe <em>Le</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getComparisonOperator()
 * @model
 * @generated
 */
public interface ComparisonOperator extends EObject
{
  /**
   * Returns the value of the '<em><b>Gt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gt</em>' attribute.
   * @see #setGt(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getComparisonOperator_Gt()
   * @model
   * @generated
   */
  String getGt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getGt <em>Gt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gt</em>' attribute.
   * @see #getGt()
   * @generated
   */
  void setGt(String value);

  /**
   * Returns the value of the '<em><b>Ge</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ge</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ge</em>' attribute.
   * @see #setGe(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getComparisonOperator_Ge()
   * @model
   * @generated
   */
  String getGe();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getGe <em>Ge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ge</em>' attribute.
   * @see #getGe()
   * @generated
   */
  void setGe(String value);

  /**
   * Returns the value of the '<em><b>Eq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Eq</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eq</em>' attribute.
   * @see #setEq(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getComparisonOperator_Eq()
   * @model
   * @generated
   */
  String getEq();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getEq <em>Eq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eq</em>' attribute.
   * @see #getEq()
   * @generated
   */
  void setEq(String value);

  /**
   * Returns the value of the '<em><b>Neq</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Neq</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neq</em>' attribute.
   * @see #setNeq(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getComparisonOperator_Neq()
   * @model
   * @generated
   */
  String getNeq();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getNeq <em>Neq</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neq</em>' attribute.
   * @see #getNeq()
   * @generated
   */
  void setNeq(String value);

  /**
   * Returns the value of the '<em><b>Lt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lt</em>' attribute.
   * @see #setLt(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getComparisonOperator_Lt()
   * @model
   * @generated
   */
  String getLt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getLt <em>Lt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lt</em>' attribute.
   * @see #getLt()
   * @generated
   */
  void setLt(String value);

  /**
   * Returns the value of the '<em><b>Le</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Le</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Le</em>' attribute.
   * @see #setLe(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getComparisonOperator_Le()
   * @model
   * @generated
   */
  String getLe();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.ComparisonOperator#getLe <em>Le</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Le</em>' attribute.
   * @see #getLe()
   * @generated
   */
  void setLe(String value);

} // ComparisonOperator
