/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudeFactory
 * @model kind="package"
 * @generated
 */
public interface Esper2MaudePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "esper2Maude";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Esper2Maude";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "esper2Maude";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Esper2MaudePackage eINSTANCE = org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.esper2Maude.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.esper2Maude.impl.ModelImpl
   * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Patterns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PATTERNS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.esper2Maude.impl.PatternImpl <em>Pattern</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.esper2Maude.impl.PatternImpl
   * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getPattern()
   * @generated
   */
  int PATTERN = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN__NAME = 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN__EVENT = 1;

  /**
   * The feature id for the '<em><b>Select Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN__SELECT_ENTRIES = 2;

  /**
   * The feature id for the '<em><b>Select Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN__SELECT_ENTRY = 3;

  /**
   * The number of structural features of the '<em>Pattern</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.esper2Maude.impl.NonLastSelectEntryImpl <em>Non Last Select Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.esper2Maude.impl.NonLastSelectEntryImpl
   * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getNonLastSelectEntry()
   * @generated
   */
  int NON_LAST_SELECT_ENTRY = 2;

  /**
   * The feature id for the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LAST_SELECT_ENTRY__ENTRY = 0;

  /**
   * The number of structural features of the '<em>Non Last Select Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_LAST_SELECT_ENTRY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.esper2Maude.impl.LastSelectEntryImpl <em>Last Select Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.esper2Maude.impl.LastSelectEntryImpl
   * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getLastSelectEntry()
   * @generated
   */
  int LAST_SELECT_ENTRY = 3;

  /**
   * The feature id for the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAST_SELECT_ENTRY__ENTRY = 0;

  /**
   * The number of structural features of the '<em>Last Select Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAST_SELECT_ENTRY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.esper2Maude.impl.SelectEntryImpl <em>Select Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.esper2Maude.impl.SelectEntryImpl
   * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getSelectEntry()
   * @generated
   */
  int SELECT_ENTRY = 4;

  /**
   * The feature id for the '<em><b>Field</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ENTRY__FIELD = 0;

  /**
   * The feature id for the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ENTRY__ALIAS = 1;

  /**
   * The feature id for the '<em><b>Group Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ENTRY__GROUP_OP = 2;

  /**
   * The number of structural features of the '<em>Select Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ENTRY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.esper2Maude.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.esper2Maude.impl.FieldImpl
   * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getField()
   * @generated
   */
  int FIELD = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.esper2Maude.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.esper2Maude.Model#getPatterns <em>Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Patterns</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Model#getPatterns()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Patterns();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.esper2Maude.Pattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Pattern
   * @generated
   */
  EClass getPattern();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Pattern#getName()
   * @see #getPattern()
   * @generated
   */
  EAttribute getPattern_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Pattern#getEvent()
   * @see #getPattern()
   * @generated
   */
  EAttribute getPattern_Event();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getSelectEntries <em>Select Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Select Entries</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Pattern#getSelectEntries()
   * @see #getPattern()
   * @generated
   */
  EReference getPattern_SelectEntries();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getSelectEntry <em>Select Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Select Entry</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Pattern#getSelectEntry()
   * @see #getPattern()
   * @generated
   */
  EReference getPattern_SelectEntry();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.esper2Maude.NonLastSelectEntry <em>Non Last Select Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Non Last Select Entry</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.NonLastSelectEntry
   * @generated
   */
  EClass getNonLastSelectEntry();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.esper2Maude.NonLastSelectEntry#getEntry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entry</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.NonLastSelectEntry#getEntry()
   * @see #getNonLastSelectEntry()
   * @generated
   */
  EReference getNonLastSelectEntry_Entry();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.esper2Maude.LastSelectEntry <em>Last Select Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Last Select Entry</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.LastSelectEntry
   * @generated
   */
  EClass getLastSelectEntry();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.esper2Maude.LastSelectEntry#getEntry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entry</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.LastSelectEntry#getEntry()
   * @see #getLastSelectEntry()
   * @generated
   */
  EReference getLastSelectEntry_Entry();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.esper2Maude.SelectEntry <em>Select Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Entry</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.SelectEntry
   * @generated
   */
  EClass getSelectEntry();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.esper2Maude.SelectEntry#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Field</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.SelectEntry#getField()
   * @see #getSelectEntry()
   * @generated
   */
  EReference getSelectEntry_Field();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.esper2Maude.SelectEntry#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alias</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.SelectEntry#getAlias()
   * @see #getSelectEntry()
   * @generated
   */
  EAttribute getSelectEntry_Alias();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.esper2Maude.SelectEntry#getGroupOp <em>Group Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group Op</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.SelectEntry#getGroupOp()
   * @see #getSelectEntry()
   * @generated
   */
  EAttribute getSelectEntry_GroupOp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.esper2Maude.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.esper2Maude.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.esper2Maude.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Esper2MaudeFactory getEsper2MaudeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.esper2Maude.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.esper2Maude.impl.ModelImpl
     * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Patterns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PATTERNS = eINSTANCE.getModel_Patterns();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.esper2Maude.impl.PatternImpl <em>Pattern</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.esper2Maude.impl.PatternImpl
     * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getPattern()
     * @generated
     */
    EClass PATTERN = eINSTANCE.getPattern();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATTERN__NAME = eINSTANCE.getPattern_Name();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATTERN__EVENT = eINSTANCE.getPattern_Event();

    /**
     * The meta object literal for the '<em><b>Select Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN__SELECT_ENTRIES = eINSTANCE.getPattern_SelectEntries();

    /**
     * The meta object literal for the '<em><b>Select Entry</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN__SELECT_ENTRY = eINSTANCE.getPattern_SelectEntry();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.esper2Maude.impl.NonLastSelectEntryImpl <em>Non Last Select Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.esper2Maude.impl.NonLastSelectEntryImpl
     * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getNonLastSelectEntry()
     * @generated
     */
    EClass NON_LAST_SELECT_ENTRY = eINSTANCE.getNonLastSelectEntry();

    /**
     * The meta object literal for the '<em><b>Entry</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_LAST_SELECT_ENTRY__ENTRY = eINSTANCE.getNonLastSelectEntry_Entry();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.esper2Maude.impl.LastSelectEntryImpl <em>Last Select Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.esper2Maude.impl.LastSelectEntryImpl
     * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getLastSelectEntry()
     * @generated
     */
    EClass LAST_SELECT_ENTRY = eINSTANCE.getLastSelectEntry();

    /**
     * The meta object literal for the '<em><b>Entry</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAST_SELECT_ENTRY__ENTRY = eINSTANCE.getLastSelectEntry_Entry();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.esper2Maude.impl.SelectEntryImpl <em>Select Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.esper2Maude.impl.SelectEntryImpl
     * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getSelectEntry()
     * @generated
     */
    EClass SELECT_ENTRY = eINSTANCE.getSelectEntry();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_ENTRY__FIELD = eINSTANCE.getSelectEntry_Field();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_ENTRY__ALIAS = eINSTANCE.getSelectEntry_Alias();

    /**
     * The meta object literal for the '<em><b>Group Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_ENTRY__GROUP_OP = eINSTANCE.getSelectEntry_GroupOp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.esper2Maude.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.esper2Maude.impl.FieldImpl
     * @see org.xtext.example.mydsl.esper2Maude.impl.Esper2MaudePackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

  }

} //Esper2MaudePackage
