/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter From</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getFollowedBy <em>Followed By</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getRight <em>Right</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getEventVariable <em>Event Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getEventName <em>Event Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom()
 * @model
 * @generated
 */
public interface FilterFrom extends EObject
{
  /**
   * Returns the value of the '<em><b>Followed By</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Followed By</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Followed By</em>' containment reference.
   * @see #setFollowedBy(FollowedBy)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom_FollowedBy()
   * @model containment="true"
   * @generated
   */
  FollowedBy getFollowedBy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getFollowedBy <em>Followed By</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Followed By</em>' containment reference.
   * @see #getFollowedBy()
   * @generated
   */
  void setFollowedBy(FollowedBy value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(FilterFrom)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom_Left()
   * @model containment="true"
   * @generated
   */
  FilterFrom getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(FilterFrom value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference.
   * @see #setOp(LogicalOperator)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom_Op()
   * @model containment="true"
   * @generated
   */
  LogicalOperator getOp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getOp <em>Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' containment reference.
   * @see #getOp()
   * @generated
   */
  void setOp(LogicalOperator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(FilterFrom)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom_Right()
   * @model containment="true"
   * @generated
   */
  FilterFrom getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(FilterFrom value);

  /**
   * Returns the value of the '<em><b>Event Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Variable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Variable</em>' attribute.
   * @see #setEventVariable(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom_EventVariable()
   * @model
   * @generated
   */
  String getEventVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getEventVariable <em>Event Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Variable</em>' attribute.
   * @see #getEventVariable()
   * @generated
   */
  void setEventVariable(String value);

  /**
   * Returns the value of the '<em><b>Event Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Name</em>' attribute.
   * @see #setEventName(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom_EventName()
   * @model
   * @generated
   */
  String getEventName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getEventName <em>Event Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Name</em>' attribute.
   * @see #getEventName()
   * @generated
   */
  void setEventName(String value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(FilterEvent)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterFrom_Filter()
   * @model containment="true"
   * @generated
   */
  FilterEvent getFilter();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterFrom#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(FilterEvent value);

} // FilterFrom
