/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getEventPropName <em>Event Prop Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getEventVariable <em>Event Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getNeg <em>Neg</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getNum <em>Num</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getDec <em>Dec</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getT <em>T</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getF <em>F</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart()
 * @model
 * @generated
 */
public interface FilterPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Event Prop Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Prop Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Prop Name</em>' attribute.
   * @see #setEventPropName(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_EventPropName()
   * @model
   * @generated
   */
  String getEventPropName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getEventPropName <em>Event Prop Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Prop Name</em>' attribute.
   * @see #getEventPropName()
   * @generated
   */
  void setEventPropName(String value);

  /**
   * Returns the value of the '<em><b>Event Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Variable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Variable</em>' attribute.
   * @see #setEventVariable(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_EventVariable()
   * @model
   * @generated
   */
  String getEventVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getEventVariable <em>Event Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Variable</em>' attribute.
   * @see #getEventVariable()
   * @generated
   */
  void setEventVariable(String value);

  /**
   * Returns the value of the '<em><b>Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Neg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neg</em>' attribute.
   * @see #setNeg(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_Neg()
   * @model
   * @generated
   */
  String getNeg();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getNeg <em>Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neg</em>' attribute.
   * @see #getNeg()
   * @generated
   */
  void setNeg(String value);

  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(int)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_Num()
   * @model
   * @generated
   */
  int getNum();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(int value);

  /**
   * Returns the value of the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dec</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec</em>' attribute.
   * @see #setDec(int)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_Dec()
   * @model
   * @generated
   */
  int getDec();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getDec <em>Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec</em>' attribute.
   * @see #getDec()
   * @generated
   */
  void setDec(int value);

  /**
   * Returns the value of the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Str</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' attribute.
   * @see #setStr(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_Str()
   * @model
   * @generated
   */
  String getStr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getStr <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' attribute.
   * @see #getStr()
   * @generated
   */
  void setStr(String value);

  /**
   * Returns the value of the '<em><b>T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>T</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' attribute.
   * @see #setT(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_T()
   * @model
   * @generated
   */
  String getT();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getT <em>T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' attribute.
   * @see #getT()
   * @generated
   */
  void setT(String value);

  /**
   * Returns the value of the '<em><b>F</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' attribute.
   * @see #setF(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterPart_F()
   * @model
   * @generated
   */
  String getF();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterPart#getF <em>F</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' attribute.
   * @see #getF()
   * @generated
   */
  void setF(String value);

} // FilterPart
