/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterOperator#getComparison <em>Comparison</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FilterOperator#getLogical <em>Logical</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterOperator()
 * @model
 * @generated
 */
public interface FilterOperator extends EObject
{
  /**
   * Returns the value of the '<em><b>Comparison</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comparison</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison</em>' containment reference.
   * @see #setComparison(ComparisonOperator)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterOperator_Comparison()
   * @model containment="true"
   * @generated
   */
  ComparisonOperator getComparison();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterOperator#getComparison <em>Comparison</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison</em>' containment reference.
   * @see #getComparison()
   * @generated
   */
  void setComparison(ComparisonOperator value);

  /**
   * Returns the value of the '<em><b>Logical</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Logical</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logical</em>' containment reference.
   * @see #setLogical(LogicalOperator)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFilterOperator_Logical()
   * @model containment="true"
   * @generated
   */
  LogicalOperator getLogical();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FilterOperator#getLogical <em>Logical</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logical</em>' containment reference.
   * @see #getLogical()
   * @generated
   */
  void setLogical(LogicalOperator value);

} // FilterOperator
