/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Followed By</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FollowedBy#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FollowedBy#getRight <em>Right</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.FollowedBy#getWhereFilter <em>Where Filter</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFollowedBy()
 * @model
 * @generated
 */
public interface FollowedBy extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SubFilterFollowedBy)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFollowedBy_Left()
   * @model containment="true"
   * @generated
   */
  SubFilterFollowedBy getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FollowedBy#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SubFilterFollowedBy value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(SubFilterFollowedBy)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFollowedBy_Right()
   * @model containment="true"
   * @generated
   */
  SubFilterFollowedBy getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FollowedBy#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(SubFilterFollowedBy value);

  /**
   * Returns the value of the '<em><b>Where Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Where Filter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where Filter</em>' containment reference.
   * @see #setWhereFilter(WhereFilter)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getFollowedBy_WhereFilter()
   * @model containment="true"
   * @generated
   */
  WhereFilter getWhereFilter();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.FollowedBy#getWhereFilter <em>Where Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Where Filter</em>' containment reference.
   * @see #getWhereFilter()
   * @generated
   */
  void setWhereFilter(WhereFilter value);

} // FollowedBy
