/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Last Select Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.LastSelectEntry#getEntry <em>Entry</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getLastSelectEntry()
 * @model
 * @generated
 */
public interface LastSelectEntry extends EObject
{
  /**
   * Returns the value of the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entry</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entry</em>' containment reference.
   * @see #setEntry(SelectEntry)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getLastSelectEntry_Entry()
   * @model containment="true"
   * @generated
   */
  SelectEntry getEntry();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.LastSelectEntry#getEntry <em>Entry</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entry</em>' containment reference.
   * @see #getEntry()
   * @generated
   */
  void setEntry(SelectEntry value);

} // LastSelectEntry
