/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.LogicalOperator#getAnd <em>And</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.LogicalOperator#getOr <em>Or</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getLogicalOperator()
 * @model
 * @generated
 */
public interface LogicalOperator extends EObject
{
  /**
   * Returns the value of the '<em><b>And</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>And</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>And</em>' attribute.
   * @see #setAnd(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getLogicalOperator_And()
   * @model
   * @generated
   */
  String getAnd();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.LogicalOperator#getAnd <em>And</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>And</em>' attribute.
   * @see #getAnd()
   * @generated
   */
  void setAnd(String value);

  /**
   * Returns the value of the '<em><b>Or</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Or</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Or</em>' attribute.
   * @see #setOr(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getLogicalOperator_Or()
   * @model
   * @generated
   */
  String getOr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.LogicalOperator#getOr <em>Or</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Or</em>' attribute.
   * @see #getOr()
   * @generated
   */
  void setOr(String value);

} // LogicalOperator
