/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Pattern#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Pattern#getNum <em>Num</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Pattern#getEvent <em>Event</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Pattern#getSelectEntries <em>Select Entries</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Pattern#getSelectEntry <em>Select Entry</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Pattern#getFromFilter <em>From Filter</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Pattern#getWin <em>Win</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern()
 * @model
 * @generated
 */
public interface Pattern extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(int)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern_Num()
   * @model
   * @generated
   */
  int getNum();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(int value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference.
   * @see #setEvent(Event)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern_Event()
   * @model containment="true"
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getEvent <em>Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' containment reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

  /**
   * Returns the value of the '<em><b>Select Entries</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.esper2Maude.NonLastSelectEntry}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Select Entries</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Select Entries</em>' containment reference list.
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern_SelectEntries()
   * @model containment="true"
   * @generated
   */
  EList<NonLastSelectEntry> getSelectEntries();

  /**
   * Returns the value of the '<em><b>Select Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Select Entry</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Select Entry</em>' containment reference.
   * @see #setSelectEntry(LastSelectEntry)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern_SelectEntry()
   * @model containment="true"
   * @generated
   */
  LastSelectEntry getSelectEntry();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getSelectEntry <em>Select Entry</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Select Entry</em>' containment reference.
   * @see #getSelectEntry()
   * @generated
   */
  void setSelectEntry(LastSelectEntry value);

  /**
   * Returns the value of the '<em><b>From Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From Filter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Filter</em>' containment reference.
   * @see #setFromFilter(FilterFrom)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern_FromFilter()
   * @model containment="true"
   * @generated
   */
  FilterFrom getFromFilter();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getFromFilter <em>From Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Filter</em>' containment reference.
   * @see #getFromFilter()
   * @generated
   */
  void setFromFilter(FilterFrom value);

  /**
   * Returns the value of the '<em><b>Win</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Win</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Win</em>' containment reference.
   * @see #setWin(Window)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getPattern_Win()
   * @model containment="true"
   * @generated
   */
  Window getWin();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Pattern#getWin <em>Win</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Win</em>' containment reference.
   * @see #getWin()
   * @generated
   */
  void setWin(Window value);

} // Pattern
