/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Filter Followed By</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getEventVariable <em>Event Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getEventName <em>Event Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getFilter <em>Filter</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getEvery <em>Every</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getSubFilterFollowedBy()
 * @model
 * @generated
 */
public interface SubFilterFollowedBy extends EObject
{
  /**
   * Returns the value of the '<em><b>Event Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Variable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Variable</em>' attribute.
   * @see #setEventVariable(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getSubFilterFollowedBy_EventVariable()
   * @model
   * @generated
   */
  String getEventVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getEventVariable <em>Event Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Variable</em>' attribute.
   * @see #getEventVariable()
   * @generated
   */
  void setEventVariable(String value);

  /**
   * Returns the value of the '<em><b>Event Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Name</em>' attribute.
   * @see #setEventName(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getSubFilterFollowedBy_EventName()
   * @model
   * @generated
   */
  String getEventName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getEventName <em>Event Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Name</em>' attribute.
   * @see #getEventName()
   * @generated
   */
  void setEventName(String value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(FilterEvent)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getSubFilterFollowedBy_Filter()
   * @model containment="true"
   * @generated
   */
  FilterEvent getFilter();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(FilterEvent value);

  /**
   * Returns the value of the '<em><b>Every</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Every</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Every</em>' containment reference.
   * @see #setEvery(Every)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getSubFilterFollowedBy_Every()
   * @model containment="true"
   * @generated
   */
  Every getEvery();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.SubFilterFollowedBy#getEvery <em>Every</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Every</em>' containment reference.
   * @see #getEvery()
   * @generated
   */
  void setEvery(Every value);

} // SubFilterFollowedBy
