/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.esper2Maude;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Window</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Window#getTypeTime <em>Type Time</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Window#getNum <em>Num</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper2Maude.Window#getTypeBatch <em>Type Batch</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getWindow()
 * @model
 * @generated
 */
public interface Window extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Time</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Time</em>' attribute.
   * @see #setTypeTime(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getWindow_TypeTime()
   * @model
   * @generated
   */
  String getTypeTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Window#getTypeTime <em>Type Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Time</em>' attribute.
   * @see #getTypeTime()
   * @generated
   */
  void setTypeTime(String value);

  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(int)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getWindow_Num()
   * @model
   * @generated
   */
  int getNum();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Window#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(int value);

  /**
   * Returns the value of the '<em><b>Type Batch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Batch</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Batch</em>' attribute.
   * @see #setTypeBatch(String)
   * @see org.xtext.example.mydsl.esper2Maude.Esper2MaudePackage#getWindow_TypeBatch()
   * @model
   * @generated
   */
  String getTypeBatch();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper2Maude.Window#getTypeBatch <em>Type Batch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Batch</em>' attribute.
   * @see #getTypeBatch()
   * @generated
   */
  void setTypeBatch(String value);

} // Window
